### PR TITLE
[Fixes for] Expose LDProvider as a standalone component

### PR DESCRIPTION
**Pull request by Morton**
This PR basically fixes the comments in https://github.com/launchdarkly/react-client-sdk/pull/28

### CODE REVIEW

**Comment by yusinto** [comment]
Hi @Morton thank you for helping out and fixing these. The changes you’ve made here look good, but we’d like to address [these](https://github.com/launchdarkly/react-client-sdk/pull/28#pullrequestreview-369935118) other requests too before merging the changes. The first is to add an example app in the examples folder to exemplify the use of the new `Provider` component. The second is to document this in our docs site.

**Comment by Morton** [comment]
Hi @yusinto,
I understand and I don't mind contributing fixes. But my company is using (and paying) @launchdarkly so we don't need to build documentation and examples for our devs on our own 😉 

Thanks
Morton

**Comment by bwoskow-ld** [comment]
Hi @Morton ,

We understand where you're coming from -- your position is reasonable. The intent behind Yus's message was that each incremental contribution progresses the PR closer to meeting our criteria for being merged and released in an upcoming SDK version. If you have the bandwidth, and if the example code is contributed, then we'll be able to merge and release your changes more quickly.

As for the documentation -- it lives in a [separate repository](https://github.com/launchdarkly/LaunchDarkly-Docs/blob/master/src/content/topics/sdk/client-side/react/index.mdx) and can definitely be a follow-up task for the SDK team once this PR is merged and ready to be released in an SDK version.

Cheers,
Ben

**Comment by bwoskow-ld** [comment]
Hi @Morton ,

Thanks again for making these changes. We've gone ahead and resolved merge conflicts which arose while your PR was sitting here. We're going to go ahead and merge this now. The SDK team will take on the remaining tasks mentioned above (example code sample + documentation). 

This change will be included in the next React SDK release which we will aim to release in the upcoming week or two.

**Pull request merged**
