### PR TITLE
Add react 17 peer dependency

### PR DESCRIPTION
**Pull request by maclockard**
**Requirements**

- [ ] I have added test coverage for new or changed functionality
- [x] I have followed the repository's [pull request submission guidelines](../blob/master/CONTRIBUTING.md#submitting-pull-requests)
- [ ] I have validated my changes against all supported platform versions

**Additional context**

https://reactjs.org/blog/2020/10/20/react-v17.html

### CODE REVIEW

**Comment by bwoskow-ld** [comment]
Hi @maclockard,

Thanks for the pull request. We'll need to verify that the SDK doesn't have any unexpected issues with React 17. If that testing is fine then we'll move forward with this change.

_Filed internally as 103643._

Cheers,
@bwoskow-ld

**Comment by maclockard** [comment]
Awesome, thank you!

**Comment by bwoskow-ld** [comment]
Hi @maclockard ,

Thanks for pointing out this issue and proposing a fix. Our testing showed that the fix was a bit more involved than just this one-line peer dependency; as such I'll merge your pull request onto a temporary `contrib` branch and will then include it plus the additional changes in the next release.

Cheers,
@bwoskow-ld

**Comment by maclockard** [comment]
Awesome, thank you!

**Comment by bwoskow-ld** [comment]
This is resolved in [2.22.2](https://github.com/launchdarkly/react-client-sdk/releases/tag/2.22.2).

**Pull request merged**
